CREATE TABLE KUNDE (
  KUNDEN_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  REGISTRIERUNGSDATUM DATE,
  KUNDEN_STATUS BOOLEAN,
  NEUKUNDE BOOLEAN
);

DROP TABLE kunde;

DELETE FROM kunde;

TRUNCATE kunde;

ALTER TABLE kunde
ALTER COLUMN kunden_id
ADD GENERATED ALWAYS AS IDENTITY;

INSERT INTO kunde (
    NAME,
    EMAIL,
    REGISTRIERUNGSDATUM,
    KUNDEN_STATUS,
    NEUKUNDE
  )
VALUES (
    'Cristo Feig',
    'cf.vs@test.de',
    '2026-01-12',
    TRUE,
    false
  );