CREATE TABLE BESTELLPOSITION (
  BESTELLPOSITION_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  BESTELL_ID INT REFERENCES BESTELLUNG,
  PRODUKT VARCHAR(255),
  PREIS DECIMAL(10,2),
  RABATT DECIMAL(3,2) default 0.0,
  MENGE INT DEFAULT 1
)